[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#07090e"
secondaryBackgroundColor = "#121826"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
